PUT http://localhost:3003/api/blogs/65c76daa3f0bfeed7a90ccfc HTTP/1.1
content-type: application/json

{
  "title": "PUT test",
  "author": "author test123",
  "url": "url test123",
  "likes": 1004
}

